### ISSUE TITLE
Jump to event only show events related to its timeline

### ISSUE THREAD

**Issue by AnidemDex** [AnidemDex/Godot-DialogPlugin#11]
If you try to jump to another event inside an `conditional` event, you only can jump to events _inside_ the condition, not in the timeline that is out of it.

**Comment by AnidemDex** [comment]
It is obvious that this is its usual operation, and in reality it is working as it should, rather it should change the operation of the event.

**Comment by Crystalwarrior** [comment]
Jump to Event no longer even shows any events period, just letting you choose a number in a spinbox

**Comment by AnidemDex** [comment]
> Jump to Event no longer even shows any events period, just letting you choose a number in a spinbox

This is due how events are generated right now, no problem there (at least, not in code side, but in design side instead)

**Comment by AnidemDex** [comment]
Ok, I think we can use `change timeline` event with the `start in event` to choose the event outside the condition

**Comment by AnidemDex** [comment]
> Ok, I think we can use `change timeline` event with the `start in event` to choose the event outside the condition

Yep, we can use that. Closing this issue in favor of that alternative.

**Note:** Needs to be documented
