### ISSUE TITLE
Question event doesn't display anything in the editor

### ISSUE THREAD

**Issue by AnidemDex** [AnidemDex/Godot-DialogPlugin#23]
Was working in v0.2, maybe the v0.3 broke its event node and need to be redone.

**Comment by Crystalwarrior** [comment]
Seems like fixing IF|ELSE should be priority before tackling this
https://github.com/AnidemDex/Godot-DialogPlugin/issues/28
https://github.com/AnidemDex/Godot-DialogPlugin/issues/29
https://github.com/AnidemDex/Godot-DialogPlugin/issues/31
