### ISSUE TITLE
Improve Character Editor

### ISSUE THREAD

**Issue by AnidemDex** [AnidemDex/Godot-DialogPlugin#24]
- [x] #37
- [x] #38
- [x] Add a color indicator
- [x] Review load time from portraits.
- [x] Save the same way as the TimelineEditor

Edit:
I also want to move the whole editor dock to the main editor. Clever and simple (but a nightmare to implement)

**Comment by Crystalwarrior** [comment]
> Remove alternative name editor from Character Editor (to use the editor integrated one instead)
Why not rename "alternative name" to "default name", so when a text event is associated with that character, the showname that shows up is default unless overridden by the text event's showname?

>  Remove icon selector from Character Editor (same as above)
There is no editor-integrated icon selector, is there? I don't think we should remove the character icon selector.

**Comment by AnidemDex** [comment]
> Why not rename "alternative name" to "default name"...
Becasue default name was the same name as the resource, but since both of them (alternative and default) are exposed in the editor, I'll use those instead.

> There is no editor-integrated icon selector, is there? I don't think we should remove the character icon selector.
It is, that's why I'm removing it, the icon frame will be a displayer only
