### ISSUE TITLE
IF|ELSE Event Node visual duplication after re-loading the Event

### ISSUE THREAD

**Issue by Crystalwarrior** [AnidemDex/Godot-DialogPlugin#28]
IF|ELSE node visually duplicates events any time the IF|ELSE resource is Loaded into UI - this is not exclusive to drag & drop events

https://user-images.githubusercontent.com/3470436/131582987-b993e16d-e319-4ab5-b8a2-31bf7bffe9d7.mp4

**Comment by AnidemDex** [comment]
_Future note: This is due how `load_event()` is being called (being called two times at once for the same event)_

**Comment by AnidemDex** [comment]
@Crystalwarrior is this still happening?

**Comment by Crystalwarrior** [comment]
Resolved!
