### ISSUE TITLE
IF|ELSE Event node causes major lag when carried around with it having any events

### ISSUE THREAD

**Issue by Crystalwarrior** [AnidemDex/Godot-DialogPlugin#29]
IF|ELSE nodes are very expensive to drag around, causing major lag to the program - maybe drag&drop should be remade to only have a reference to the dragged event and not physically deleting it? (so the Drag&Drop data dictionary doesn't carry any information besides node index)

https://user-images.githubusercontent.com/3470436/131583320-ec382515-c79f-431e-875f-d0dda9d12497.mp4

**Comment by Crystalwarrior** [comment]
https://github.com/AnidemDex/Godot-DialogPlugin/issues/28

**Comment by AnidemDex** [comment]
_Future note: Change the `drag_data()` behaviour to avoid this in all events_
