### ISSUE TITLE
IF|ELSE Event should have expandable splits to control height of sub-timeline

### ISSUE THREAD

**Issue by Crystalwarrior** [AnidemDex/Godot-DialogPlugin#31]
This should allow users to at least edit the sub-timelines without a massive headache it is right now with a very tiny window:
![image](https://user-images.githubusercontent.com/3470436/131583249-9b1d4efc-2b3c-4720-99c3-b69a65f6307a.png)

**Comment by AnidemDex** [comment]
I have no idea how to implement this automatically.

_**Note for the future**: You probably has to make a custom node for this one 🤷‍♂️_

**Comment by AnidemDex** [comment]
Fixed by https://github.com/AnidemDex/Godot-EventSystem in EventManager node

All future Event/Timeline related issues will be moved to that repository
