### ISSUE TITLE
DialogTimelineResource icon shows up in "Add Resource" but not File Browser

### ISSUE THREAD

**Issue by Crystalwarrior** [AnidemDex/Godot-DialogPlugin#33]
![image](https://user-images.githubusercontent.com/3470436/131583669-1bbb03fa-8d5f-438c-8f62-87aff169522d.png)

**Comment by AnidemDex** [comment]
This is a thing in the Godot side (https://github.com/godotengine/godot/issues/32706), can't be fixed in the plugin for now
