### ISSUE TITLE
Character, Database and Portrait resources lack icons

### ISSUE THREAD

**Issue by Crystalwarrior** [AnidemDex/Godot-DialogPlugin#34]
It's also not very clear if anything besides Timeline and Character resources should ever be instanced by the user
![image](https://user-images.githubusercontent.com/3470436/131583706-49062ee4-768d-4a3b-a7cb-b3e482d17d9f.png)

**Comment by AnidemDex** [comment]
Bruh, I forgot to remove `DialogDatabaseResource` since is not being used anymore

**Comment by AnidemDex** [comment]
About what can be and what can not be instanced by the user: They can create any of those resources without problems. Icons must be updated anyway
