### ISSUE TITLE
Bad size when adding DialogNode

### ISSUE THREAD

**Issue by CyberRedX** [AnidemDex/Godot-DialogPlugin#51]
### OS

Windows 10 x64

### Godot Version

3.3.3

### Plugin Version

1.0 (lastest)

### Issue description

![image](https://user-images.githubusercontent.com/80461601/142877620-b3bb1b44-dd68-47ec-a412-0254de924ea0.png)
My code:
```gdscript
func _ready():
	# Creates a new DialogNode instance
	var dialog_node = DialogNode.instance()
	# Add the node as child
	add_child(dialog_node)
	# Shows the dialog node
	dialog_node.show()
	# Show an string. BBCode works too!
	dialog_node.show_text("Hello world")`
```
### Steps to reproduce

1 create an empty project
2 add textalog as plugin
3 new scene
4 add code
5 run

_**Bug squad:** Message edited to add a proper code format_

**Comment by AnidemDex** [comment]
Hey @CyberRedX did you tried to add DialogNode as child of a Node2D?

If that was the case, you need to:
- Add it as child of a canvas layer
or
- Resize it after adding it as child

Control and Node2D nodes are not compatible types, and mixing them usually leads this kinds of problems

**Comment by MMLich** [comment]
I had the exact same issue. Your solution did work. I think this should be mentioned in the readme. Thank you!

**Comment by CyberRedX** [comment]
After adding this to canvas it's working correctly, thanks!
And yeah, I too think this should be mentioned in the readme

**Comment by AnidemDex** [comment]
@CyberRedX Please close this issue if its solved. If you like, can open an issue proposal to add this information in the readme (or leave it as is, I'll add it later in the new release)
