### ISSUE TITLE
Rename the plugin

### ISSUE THREAD

**Issue by AnidemDex** [AnidemDex/Godot-DialogPlugin#8]
There's actually another plugin named "Dialog Plugin" in the asset library.

¿Quien fue el chistoso que se le ocurrió que era buena idea nombrar el plugin de forma tan generica?

Anyway, I'm out of ideas and need tho think about this. I don't know if is really an issue.

**Comment by AnidemDex** [comment]
After a long (not too long) brainstorm, the tentative proposal is **`Textalog`** (provided by @crystalwarrior )

Is far better than other ideas (like `Dialogger` or `Cool Text Parser`).

**Comment by Crystalwarrior** [comment]
Aww yeah, Textalog! We actually came up w/ it together with CrazyJC practically at the same time LOL

**Comment by AnidemDex** [comment]
Textalog will be
