### ISSUE TITLE
About the license

### ISSUE THREAD

**Issue by AnidemDex** [AnidemDex/Godot-DialogPlugin#9]
I'm pretty sure that there are some remaining parts of dialogic in this repo. I need to update the LICENSE file according to [this tweet](https://twitter.com/Akien/status/1396880398760693765?s=20).

**Comment by Crystalwarrior** [comment]
Why not just remove the code that is reused? I don't think we really need any Dialogic code anymore

**Comment by AnidemDex** [comment]
> Why not just remove the code that is reused? I don't think we really need any Dialogic code anymore

I'm not using Dialogic code, but I need to verify that I'm _really_ not using it to have things clear

**Comment by AnidemDex** [comment]
I can't find dialogic resources or portions of the code in this repository after comparing them. Closing
